# file: ansible-role-rtags/tasks/bear_install.yml

- name: BEAR | get from git repository
  git: repo="{{ bear_repo_url }}"
       dest="{{ bear_tmp }}"
       version="{{ bear_version }}"
  register: bear_downloaded

- name: BEAR | Create build directory
  file:
    path: "{{ bear_build_dir }}"
    state: directory

- name: BEAR | run cmake
  command: chdir="{{ bear_build_dir }}" cmake -DCMAKE_INSTALL_PREFIX={{bear_install_dir}} {{ bear_tmp }}
  # when: bear_downloaded.changed

- name: BEAR | make
  command: chdir="{{ bear_build_dir }}" make
  # when: bear_downloaded.changed

- name: BEAR | make install
  command: chdir="{{ bear_build_dir }}" make install
  # when: bear_downloaded.changed
