# file: tasks/rtags_systemd.yml

# - name: RDM | make dir for rdm daemon
#   sudo: true
#   file: path=/etc/rdm state=directory mode=0755
#   when: rtags_downloaded.changed

# - name: RDM | make /var/log/rdm
#   sudo: true
#   file: path=/var/log/rdm state=directory mode=0755
#   when: rtags_downloaded.changed

- name: RDM | Add Wrapper
  become: true
  action: template src=rdm.sh-template.j2
          dest="{{rtags_install_dir}}/bin/rdm.sh"
          mode=0775
  when: rtags_downloaded.changed

- name: RDM | make ~/.config
  become: true
  become_user: vagrant
  file: path="/home/vagrant/.config/systemd/user/" state=directory mode=0755
  when: rtags_downloaded.changed

- name: RDM | Add rdm.socket
  become: true
  become_user: vagrant
  action: template src=rdm.socket-template.j2
          dest="/home/vagrant/.config/systemd/user/rdm.socket"
  when: rtags_downloaded.changed

- name: RDM | Add rdm.service
  become: true
  become_user: vagrant
  action: template src=rdm.service-template.j2
          dest="/home/vagrant/.config/systemd/user/rdm.service"
  when: rtags_downloaded.changed

- name: RDM | Start rtagd
  become: false
  service: name=rdm state=started enabled=yes
  when: rtags_downloaded.changed
