# file: ansible-role-rtags/tasks/install.yml

- name: RTAGS | get from git repository
  git: repo="{{ rtags_repo_url }}"
       dest="{{ rtags_tmp }}"
       version="{{ rtags_version }}"
  register: rtags_downloaded

- name: RTAGS | Create build directory
  file:
    path: "{{ rtags_build_dir }}"
    state: directory

- name: RTAGS | run cmake
  command: chdir="{{ rtags_build_dir }}" cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
           -DCMAKE_INSTALL_PREFIX={{rtags_install_dir}} \
           -DLIBCLANG_LLVM_CONFIG_EXECUTABLE={{llvm_config}} {{ rtags_tmp }}
  # when: rtags_downloaded.changed

- name: RTAGS | make
  command: chdir="{{ rtags_build_dir }}" make
  # when: rtags_downloaded.changed

- name: RTAGS | make install
  command: chdir="{{ rtags_build_dir }}" make install
  # when: rtags_downloaded.changed
