# file: ansible-role-rtags/tasks/install.yml

- name: RTAGS | get from git repository
  become: true
  git: repo="{{ rtags_repo_url }}"
       dest="{{ rtags_tmp }}_{{ rtags_version }}"
       version="{{ rtags_version }}"
  register: rtags_downloaded

- name: RTAGS | Create build directory
  become: true
  file:
    path: "{{ rtags_build_dir }}"
    state: directory

- name: RTAGS | run cmake
  become: true
  command: chdir="{{ rtags_build_dir }}" cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
           -DCMAKE_C_COMPILER={{llvm_install_dir}}/bin/clang \
           -DCMAKE_CXX_COMPILER={{llvm_install_dir}}/bin/clang++ \
           -DLIBCLANG_LIBRARY={{llvm_install_dir}}/lib/libclang.so \
           -DLIBCLANG_INCLUDE_DIR={{llvm_install_dir}}/include \
           -DCMAKE_INSTALL_PREFIX={{rtags_install_dir}} \
           -DGCC_INSTALL_PREFIX={{gcc_install_dir}} \
           -DCMAKE_INSTALL_RPATH={{llvm_install_dir}}/lib \
           -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE \
           -DFORCE_BASH_COMPLETION_INSTALLATION=TRUE \
           -DCMAKE_BUILD_TYPE=Release \
           -DLIBCLANG_LLVM_CONFIG_EXECUTABLE={{llvm_install_dir}}/bin/llvm-config \
           -D_GLIBCXX_USE_CXX11_ABI=1
           "{{ rtags_tmp }}_{{ rtags_version }}"
  when: rtags_downloaded.changed

- name: RTAGS | make
  become: true
  command: chdir="{{ rtags_build_dir }}" make
  when: rtags_downloaded.changed

- name: RTAGS | make install
  become: true
  command: chdir="{{ rtags_build_dir }}" make install
  when: rtags_downloaded.changed

- name: RDM | Add to global PATH and set RTAGS_ROOT env var
  become: true
  action: template src=rdm.sh-template.j2
          dest="/etc/profile.d/rdm.sh"
          mode=0644
