# file: ansible-role-rtags/tasks/install.yml

- name: RTAGS | get from git repository
  become: true
  git: repo="{{ rtags_repo_url }}"
       dest="{{ rtags_tmp }}"
       version="{{ rtags_version }}"
  register: rtags_downloaded

- name: RTAGS | Create build directory
  become: true
  file:
    path: "{{ rtags_build_dir }}"
    state: directory

- name: RTAGS | run cmake
  become: true
  command: chdir="{{ rtags_build_dir }}" cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
           -DCMAKE_C_COMPILER={{llvm_install_dir}}/bin/clang \
           -DCMAKE_CXX_COMPILER={{llvm_install_dir}}/bin/clang++ \
           -DCMAKE_INSTALL_PREFIX={{rtags_install_dir}} \
           -DGCC_INSTALL_PREFIX={{gcc_install_dir}} \
           -DLIBCLANG_LLVM_CONFIG_EXECUTABLE={{llvm_install_dir}}/bin/llvm-config \
           {{ rtags_tmp }}
  # when: rtags_downloaded.changed

- name: RTAGS | make
  become: true
  command: chdir="{{ rtags_build_dir }}" make
  # when: rtags_downloaded.changed

- name: RTAGS | make install
  become: true
  command: chdir="{{ rtags_build_dir }}" make install
  # when: rtags_downloaded.changed

- name: RTAGS | rename rc to rc.exe
  command: mv "{{ rtags_build_dir }}/bin/rc" "{{ rtags_build_dir }}/bin/rc.exe"
  # when: rtags_downloaded.changed

- name: RDM | Add Wrapper
  become: true
  action: template src=rdm.sh-template.j2
          dest="{{rtags_install_dir}}/bin/rdm.sh"
          mode=0775
  # when: rtags_downloaded.changed

- name: RDM | Add rc wrapper
  become: true
  action: template src=rc-template.j2
          dest="{{rtags_install_dir}}/bin/rc"
          mode=0775
  # when: rtags_downloaded.changed
